
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sportShop?serverTimezone=Asia/Seoul
    username: root
    password: gustjr0227


#MyBatis
mybatis:
  type-aliases-package: com.example.SportShopProject.domain
  configuration.map-underscore-to-camel-case: true


